-- Generated by drizzle-kit from src/schema.ts. Two statements for the trade id
-- sequence are hand-written and marked HAND-WRITTEN; they must be re-applied if
-- this file is ever regenerated.
--
-- HAND-WRITTEN. Must come first: trades defaults trade_id from this sequence,
-- and a default cannot reference a sequence that does not exist yet.
-- Ids are TRD-100001 upwards, which is readable and speakable; a uuid is not.
CREATE SEQUENCE "trade_id_seq" START WITH 100001;--> statement-breakpoint
CREATE TYPE "public"."trade_event_type" AS ENUM('CREATED', 'AMENDED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."trade_side" AS ENUM('BUY', 'SELL');--> statement-breakpoint
CREATE TYPE "public"."trade_status" AS ENUM('ACTIVE', 'CANCELLED');--> statement-breakpoint
CREATE TABLE "trade_events" (
	"seq" bigserial PRIMARY KEY NOT NULL,
	"trade_id" text NOT NULL,
	"event_type" "trade_event_type" NOT NULL,
	"before" jsonb,
	"after" jsonb NOT NULL,
	"actor" text NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trades" (
	"trade_id" text PRIMARY KEY DEFAULT 'TRD-' || lpad(nextval('trade_id_seq')::text, 6, '0') NOT NULL,
	"symbol" text NOT NULL,
	"side" "trade_side" NOT NULL,
	"quantity" integer NOT NULL,
	"price" numeric(18, 6) NOT NULL,
	"trader" text NOT NULL,
	"book" text NOT NULL,
	"counterparty" text NOT NULL,
	"trade_timestamp" timestamp with time zone NOT NULL,
	"status" "trade_status" DEFAULT 'ACTIVE' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "trade_events" ADD CONSTRAINT "trade_events_trade_id_trades_trade_id_fk" FOREIGN KEY ("trade_id") REFERENCES "public"."trades"("trade_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "trade_events_trade_idx" ON "trade_events" USING btree ("trade_id","seq");--> statement-breakpoint
CREATE INDEX "trades_symbol_idx" ON "trades" USING btree ("symbol");--> statement-breakpoint
CREATE INDEX "trades_status_idx" ON "trades" USING btree ("status");--> statement-breakpoint
CREATE INDEX "trades_trader_idx" ON "trades" USING btree ("trader");--> statement-breakpoint
CREATE INDEX "trades_book_idx" ON "trades" USING btree ("book");--> statement-breakpoint
CREATE INDEX "trades_timestamp_idx" ON "trades" USING btree ("trade_timestamp" DESC NULLS LAST,"trade_id" DESC NULLS LAST);--> statement-breakpoint
-- HAND-WRITTEN, and easy to omit.
--
-- TRUNCATE ... RESTART IDENTITY only resets sequences owned by a column, and a
-- hand-created sequence is owned by nobody. Without this, the test helper
-- truncates trades but leaves the counter, so "two inserts give TRD-100001 then
-- TRD-100002" passes once on a fresh database and fails thereafter. Verified on
-- postgres:16-alpine: without it the next id is TRD-100003, with it TRD-100001.
--
-- Ownership by a text column is permitted; it tracks the default expression.
ALTER SEQUENCE "trade_id_seq" OWNED BY "trades"."trade_id";
